name: Terraform AWS Destroy

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_s3_backend_bucket: ${{ secrets.TF_S3_BUCKET }}
      TF_VAR_s3_backend_key: ${{ secrets.TF_S3_KEY }}
      TF_VAR_s3_backend_region: ${{ secrets.TF_S3_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init (S3 Backend)
        run: terraform init \
          -backend-config="bucket=${{ secrets.TF_S3_BUCKET }}" \
          -backend-config="key=${{ secrets.TF_S3_KEY }}" \
          -backend-config="region=${{ secrets.TF_S3_REGION }}"

      - name: Terraform Plan Destroy
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve